<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net7.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<RootNamespace>Magical_Magical_Dendrogram_Maker</RootNamespace>
		<AssemblyName>Magical Magical Dendrogram Maker</AssemblyName>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<PlatformTarget>x64</PlatformTarget>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>

	</PropertyGroup>

	<ItemGroup>
		<Content Include="Homology\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="iqtree\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="mafft-win\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.102.0" />
		<PackageReference Include="DocumentFormat.OpenXml" Version="2.16.0" />
		<PackageReference Update="DocumentFormat.OpenXml" Version="2.16.0" />
		<PackageReference Include="ExcelNumberFormat" Version="1.1.0" />
		<PackageReference Include="Irony.NetCore" Version="1.0.11" />
		<PackageReference Include="SixLabors.Fonts" Version="1.0.0" />
		<PackageReference Include="TreeNode" Version="1.7.0" />
		<PackageReference Include="XLParser" Version="1.5.2" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="mafft-win\**\*.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="iqtree\**\*.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="TreeViewer\**\*.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="TreeViewer\**\*.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Homology\**\*.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<None Update="homology\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="mafft-win\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="iqtree\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="TreeViewer\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
	  <Compile Remove="TreeViewer\cs\**" />
	  <Compile Remove="TreeViewer\de\**" />
	  <Compile Remove="TreeViewer\es\**" />
	  <Compile Remove="TreeViewer\fr\**" />
	  <Compile Remove="TreeViewer\Icons\**" />
	  <Compile Remove="TreeViewer\it\**" />
	  <Compile Remove="TreeViewer\ja\**" />
	  <Compile Remove="TreeViewer\ko\**" />
	  <Compile Remove="TreeViewer\pl\**" />
	  <Compile Remove="TreeViewer\pt-BR\**" />
	  <Compile Remove="TreeViewer\ru\**" />
	  <Compile Remove="TreeViewer\tr\**" />
	  <Compile Remove="TreeViewer\zh-Hans\**" />
	  <Compile Remove="TreeViewer\zh-Hant\**" />
	  <Content Remove="TreeViewer\cs\**" />
	  <Content Remove="TreeViewer\de\**" />
	  <Content Remove="TreeViewer\es\**" />
	  <Content Remove="TreeViewer\fr\**" />
	  <Content Remove="TreeViewer\Icons\**" />
	  <Content Remove="TreeViewer\it\**" />
	  <Content Remove="TreeViewer\ja\**" />
	  <Content Remove="TreeViewer\ko\**" />
	  <Content Remove="TreeViewer\pl\**" />
	  <Content Remove="TreeViewer\pt-BR\**" />
	  <Content Remove="TreeViewer\ru\**" />
	  <Content Remove="TreeViewer\tr\**" />
	  <Content Remove="TreeViewer\zh-Hans\**" />
	  <Content Remove="TreeViewer\zh-Hant\**" />
	  <EmbeddedResource Remove="TreeViewer\cs\**" />
	  <EmbeddedResource Remove="TreeViewer\de\**" />
	  <EmbeddedResource Remove="TreeViewer\es\**" />
	  <EmbeddedResource Remove="TreeViewer\fr\**" />
	  <EmbeddedResource Remove="TreeViewer\Icons\**" />
	  <EmbeddedResource Remove="TreeViewer\it\**" />
	  <EmbeddedResource Remove="TreeViewer\ja\**" />
	  <EmbeddedResource Remove="TreeViewer\ko\**" />
	  <EmbeddedResource Remove="TreeViewer\pl\**" />
	  <EmbeddedResource Remove="TreeViewer\pt-BR\**" />
	  <EmbeddedResource Remove="TreeViewer\ru\**" />
	  <EmbeddedResource Remove="TreeViewer\tr\**" />
	  <EmbeddedResource Remove="TreeViewer\zh-Hans\**" />
	  <EmbeddedResource Remove="TreeViewer\zh-Hant\**" />
	  <None Remove="TreeViewer\cs\**" />
	  <None Remove="TreeViewer\de\**" />
	  <None Remove="TreeViewer\es\**" />
	  <None Remove="TreeViewer\fr\**" />
	  <None Remove="TreeViewer\Icons\**" />
	  <None Remove="TreeViewer\it\**" />
	  <None Remove="TreeViewer\ja\**" />
	  <None Remove="TreeViewer\ko\**" />
	  <None Remove="TreeViewer\pl\**" />
	  <None Remove="TreeViewer\pt-BR\**" />
	  <None Remove="TreeViewer\ru\**" />
	  <None Remove="TreeViewer\tr\**" />
	  <None Remove="TreeViewer\zh-Hans\**" />
	  <None Remove="TreeViewer\zh-Hant\**" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="mafft-win\tmp\" />
	</ItemGroup>

</Project>
